Rework final product stream selection logic
With the potential for a plethora of generated sound files, the choice
of which ones to include becomes wider than my personal goals. What I
want to build are videos with a sinlge enhanced stereo stream. The use
of a single stream keeps the file size low, the enhanced sound helps my
ears (part of the genisis of the project), and my system only has stereo
sound available.

For usefulness to others, the system needs to be able to include any of
the generated streams, including multiple versions of them, into the
final video file. In recognition of that, the audio section in the
config file has been expanded, and reworked. The commands to create the
streams have been updated to match.

All the audio processing commands and sub-commands have been affected by
the change. There should be very limited changes needed to embed the
creation process into the final video building command. The functions
involved in the use of some, as yet unknown, codec for audio streams has
been considered, and some groundwork for that eventuality has been done.

Signed-off-by: Ronald Lamoreaux <gitkey@chindraba.work>

diff --git a/dts-build b/dts-build
--- a/dts-build
+++ b/dts-build
@@ -43,32 +43,37 @@
 source "$fixvid_dir/helpers";
 
 group='audio';
-required='dts';
-group_fields="source stream label title lang layout channels include \
-dyna_center dyna_extras dyna_origin dyna_stereo mapping mixing";
+required='stream';
+group_fields="source stream label title lang channels layout mapping \
+mixing dyna_stereo dyna_center dyna_origin dyna_extras dyna_others \
+make_ac3 include_ac3 make_aac include_aac \
+make_dts include_dts";
 
 function do_dts_build {
+  # Check for the need to make surround sound streams
+  [[ 1 = $audio_make_dts ]] || \
+  [[ 1 = $audio_include_dts ]] ||
+    return 0;
+
   # Test for surround sound and load surround sound settings
-  surround_sound_settings || return 0;
+  multi_channel_setup || return 0;
 
   # Select which source file type to use, AC3 or AAC
-  source_ext='ac3';
-  [[ 1 = $skip_ac3 ]] && [[ 1 = $skip_aac ]] && return 0;
-  [[ 1 = $skip_ac3 ]] || source_ext='aac';
+  [[ 1 != $audio_make_aac ]] && \
+  [[ 1 != $audio_include_aac ]] &&
+    extension='ac3' || extension='aac';
 
   # Skip this if it has already been done.
   # To rerun, delete the *-remix.dts file first
-echo "building $group_num";
-  [[ -s "${work_prefix}-remix.dts" ]] && return 0;
+  [[ -s "${work_prefix}-channels-remix.dts" ]] && return 0;
 
   # Check for all dependent files
   # Force hts-remix to (re)make all if one is missing
   files_ready=0;
-  [[ -s "${work_prefix}-remix.$source_ext" ]] || files_ready=1;
-  [[ -s "${work_prefix}.$source_ext" ]] || files_ready=1;
+  [[ -s "${work_prefix}-channels-remix.$extension" ]] || files_ready=1;
+  [[ -s "${work_prefix}-channels.$extension" ]] || files_ready=1;
   [[ 0 = $files_ready ]] || {
-    rm -f "${work_prefix}-remix.aac";
-    rm -f "${work_prefix}-remix.ac3";
+    rm -f "${work_prefix}-channels-remix.$extension";
     echo "Source file(s) not found.";
     echo " ... Creating ...";
     echo "";
@@ -76,10 +81,11 @@ echo "building $group_num";
   }
 
   # Skip creation of the un-normalized remix if already done
-  [[ -s "${work_prefix}.dts" ]] || multi_launch "Create ${audio_label} DTS" bash -c "FFREPORT=file='fixvid-${work_prefix}.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}.$source_ext' -map 0:0 $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_label DTS' -c:0 dts -b:a 768k -strict -2 $use_threads $output_flags '${work_prefix}.dts'";
+  [[ -s "${work_prefix}.dts" ]] || \
+    multi_launch "${audio_label} Copy  to DTS" bash -c "FFREPORT=file='fixvid-${work_prefix}-dts.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}-channels.$extension' -map 0:0 $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title DTS' -c:0 dts -b:a 768k -strict -2 $use_threads $output_flags '${work_prefix}.dts'";
 
   # Always (re-)create the normalized version
-  multi_launch "Remix ${audio_label} DTS" bash -c "FFREPORT=file='fixvid-${work_prefix}.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}-remix.$source_ext' -map 0:0 $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_label DTS' -c:0 dts -b:a 768k -strict -2 $use_threads $output_flags '${work_prefix}-remix.dts'";
+  multi_launch "${audio_label} Remix to DTS" bash -c "FFREPORT=file='fixvid-${work_prefix}-remix-dts.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}-channels-remix.$extension' -map 0:0 $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title DTS' -c:0 dts -b:a 768k -strict -2 $use_threads $output_flags '${work_prefix}-remix.dts'";
 }
 
 # Read the optional argument.
diff --git a/hts-remix b/hts-remix
--- a/hts-remix
+++ b/hts-remix
@@ -43,25 +43,45 @@ source "$fixvid_dir/helpers";
 
 group='audio';
 required='stream';
-group_fields="source stream label title lang layout channels include \
-dyna_center dyna_extras dyna_origin dyna_stereo mapping mixing";
+group_fields="source stream label title lang channels layout mapping \
+mixing dyna_stereo dyna_center dyna_origin dyna_extras dyna_others \
+make_ac3 include_ac3 make_aac include_aac \
+make_channels include_channels \
+make_dts include_dts";
 
 function do_remix {
+  # Check for the need to make surround sound streams
+  [[ 1 = $audio_make_channels ]] || \
+  [[ 1 = $audio_include_channels ]] || \
+  [[ 1 = $audio_make_dts ]] || \
+  [[ 1 = $audio_include_dts ]] ||
+    return 0;
+
   # Test for surround sound and load surround sound settings
-  surround_sound_settings || return 0;
+  multi_channel_setup || return 0;
+
+  # Set the output filename base
+  work_prefix="${work_prefix}-channels";
+
+  # Check for, and set the title of the streams
+  [[ $audio_title ]] || audio_title="$video_title surround sound";
 
   # Skip this if it has already been done.
-  # To rerun, delete the *-remix.ac3 file first
-  [[ -s "${work_prefix}-remix.ac3" ]] && return 0;
+  # To rerun, delete the *-remix.* files first
+  [[ 1 != $audio_make_ac3 ]] && \
+  [[ 1 != $audio_include_ac3 ]] && \
+    extension='aac' || extension='ac3';
+  [[ -s "${work_prefix}-remix.$extension" ]] && \
+    return 3;
 
   # Check for all dependent files
   # Force hts-normalize to (re)make all if one is missing
   files_ready=0;
   for channel in $audio_layout; do
-    [[ -s "${work_prefix}-channels-adj-$channel.wav" ]] || files_ready=1;
+    [[ -s "${work_prefix}-adj-$channel.wav" ]] || files_ready=1;
   done
   [[ 0 = $files_ready ]] || {
-    rm -f "${work_prefix}-channels-adj-fl.wav";
+    rm -f "${work_prefix}-adj-fl.wav";
     echo "Normalized files not found.";
     echo " ... Creating ...";
     echo "";
@@ -74,15 +94,19 @@ function do_remix {
   unset pad_list;
   channel_count=0;
   for channel in $audio_layout; do
-    channel_in="$input_flags -i ${work_prefix}-channels-adj-${channel}.wav";
+    channel_in="$input_flags -i ${work_prefix}-adj-${channel}.wav";
     channel_pad="[$channel_count:0]";
     channels_in="${channels_in} ${channel_in}";
     pad_list="${pad_list}${channel_pad}";
     channel_count=$(( $channel_count + 1 ));
   done
 
-  [[ 1 = $skip_aac ]] || multi_launch "Enhance ${audio_label} AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-remix-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $channels_in -filter_complex '$pad_list amerge=inputs=$channel_count [CHANNELS];[CHANNELS] $audio_maping [OUT]' -map [OUT] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title (Enhanced)' -c:0 libfdk_aac -profile:a aac_he -b:a 384k $use_threads $file_meta '${work_prefix}-remix.aac'";
-  [[ 1 = $skip_ac3 ]] || multi_launch "Enhance ${audio_label} AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-remix-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $channels_in -filter_complex '$pad_list amerge=inputs=$channel_count [CHANNELS];[CHANNELS] $audio_maping [OUT]' -map [OUT] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title (Enhanced)' -c:0 ac3 -b:a 640k $use_threads $file_meta '${work_prefix}-remix.ac3'";
+  [[ 1 = $audio_make_aac ]] || \
+  [[ 1 = $audio_include_aac ]] && \
+    multi_launch "${audio_label} Remix to AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-remix-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $channels_in -filter_complex '$pad_list amerge=inputs=$channel_count [CHANNELS];[CHANNELS] $audio_maping [OUT]' -map [OUT] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title (Enhanced)' -c:0 libfdk_aac -profile:a aac_he -b:a 384k $use_threads $file_meta '${work_prefix}-remix.aac'";
+  [[ 1 = $audio_make_ac3 ]] || \
+  [[ 1 = $audio_include_ac3 ]] && \
+    multi_launch "${audio_label} Remix to AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-remix-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $channels_in -filter_complex '$pad_list amerge=inputs=$channel_count [CHANNELS];[CHANNELS] $audio_maping [OUT]' -map [OUT] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title (Enhanced)' -c:0 ac3 -b:a 640k $use_threads $file_meta '${work_prefix}-remix.ac3'";
 
   wait
 }
