Add 7.1 surround sound and parallel processing
Add the ability to process 7.1 surround sound streams. All the `hts-*`
commands utilize a standard method of pulling the surround sound data
from the config file. Possible consideration to make it into a shared
function somewhere.

The rework of the channel processing for 7.1 ability also should make it
a simple process to add other sound layouts as needed. (Even easier if
a shared function can be created.)

Added the ability to process commands in parallel.  `FFMPEG` reportedly
is good at optimizing thread usage. My running of commands with a select
few `threads` options, including 0 (auto?) never managed to utilize my
multi-core CPU to any significant level when processing audio files. To
make better use of my system I started doing commands in parallel. To
that end I liberally copied a section of code from Stack Overflow:
[How do you run multiple programs in parallel from a bash script?](https://stackoverflow.com/a/42098494/7412956)

Gains from parallelism are margin, yet a net positive, so the change
remains. Rare conditions may result in a performance decrease, but I
believe the rare events are insufficient to remove the concept. The
process most benefited by parallelism is the multi-channel normalize
process. Video of 2h 57m with 5.1 sound using 6 (or more) parallel
processes, relative to single processes, uses ~37% less time.

The output from the `FFMPEG` commands and the updates from the process
of handling parallels often intermingles. Though it is "ugly" to see, my
purpose for the `FFMPEG` output is to see that processing _is_ happening
rather than logging or documenting the process. The log files do a good
job of that. Keeping the output "clean" left me wondering if commands
were running, and how far into the encoding they were. For the nonce, I
esteem ugly feedback more than clean silence.

Reverted the change for channel layouts. Expirements proved that the the
original version was correct, and that the sequence used by FFMPEG is
somehow internal usage, but not indicative of the arrangement within the
audio streams.

Signed-off-by: Ronald Lamoreaux <gitkey@chindraba.work>

diff --git a/hts-normalize b/hts-normalize
--- a/hts-normalize
+++ b/hts-normalize
@@ -8,7 +8,7 @@
 #  and re-encode video files to create an acceptable version for a     #
 #  standardized collection or library of videos.                       #
 #                                                                      #
-#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
+#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
 #  - All Rights Reserved                                               #
 #                                                                      #
 #  FixVid is free software; you can redistribute it and/or             #
@@ -30,15 +30,6 @@
 #                                                                      #
 ########################################################################
 
-##
-##      NOTE:
-##
-##  This file is only set up for processing of files related to a
-##  surround sound soundtrack of either 5.1 or 5.1(side). Any other type
-##  of surround sound setup, 7.1, etc., will require a complete set of
-##  command files to replace hts-split, hts-normalize, and hts-merge
-##
-
 #
 # Command script to normalize each of the independent channel files from
 # the surround sound soundtrack. Uses the files created by hts-split.
@@ -49,30 +40,25 @@
 # Reads fixvid.conf for:
 #     work_files      the prefix of filenames for work files
 #     video_title     added to the title metadata of the files
+#     channel_map     the filter used to split the stream into channels
+#     channel_list    the list of channels to process
+#     stereo_mix      the ratios for mixing surround sound to stereo
 #     timestamp       entered in the creation_time metadata for streams
 #     dyna_center     the filter to apply to the center channel
 #     dyna_front      the filter to apply to the left & right channels
 #     dyna_surround   the filter to apply to other channels
-# Reads the 6 channel files made by hts-split:
-#     *-surround-fc.wav     The front center channel from the source
-#     *-surround-fl.wav     The front left channel from the source
-#     *-surround-fr.wav     The front right channel from the source
-#     *-surround-lf.wav     The low frequency channel from the source
-#     *-surround-sl.wav     The surround left channel from the source
-#     *-surround-sr.wav     The surround right channel from the source
+#     channel_map     the filter used to split the stream into channels
+#     channel_list    the list of channels to process
+#     stereo_mix      the ratios for mixing surround sound to stereo
+# Reads the channel files made by hts-split:
+#     *-surround-*.wav     The channel from the source
 #
 # Displays the ffmpeg progress line while running and the results of the
 # time command once finished.
 #
-# Generates 8 files:
-#     fixvid-*-normal.cmd    The complete ffmpeg command to execute
-#     fixvid-*-normal.log    The captured output of the ffmpeg command
-#     *-surround-efc.wav     The front center channel from the source
-#     *-surround-efl.wav     The front left channel from the source
-#     *-surround-efr.wav     The front right channel from the source
-#     *-surround-elf.wav     The low frequency channel from the source
-#     *-surround-esl.wav     The surround left channel from the source
-#     *-surround-esl.wav     The surround right channel from the source
+# Generates 1 file plus 1 per channel:
+#     fixvid-*-normalize.log    The captured output of the ffmpeg command
+#     *-surround-*.wav          The normalized channel sound
 #
 
 # Load the configuration file
@@ -85,77 +71,65 @@ work_prefix="${work_files}-surround";
 # To rerun, delete the *_surround_fce.wav file first
 [[ -s "${work_prefix}_efc.wav" ]] && exit 3;
 
+# Set the channel data based on the chosen surround layout
+# Invalid, or missing, layout will abort the process
+case "$surround_layout" in
+  '7.1' )
+    channel_map=$channel_map_71
+    channel_list=$channel_list_71
+    stereo_mix=$stereo_mix_71
+    ;;
+  '5.1' )
+    channel_map=$channel_map_51
+    channel_list=$channel_list_51
+    stereo_mix=$stereo_mix_51
+    ;;
+  '5.1(side)' )
+    channel_map=$channel_map_51_side
+    channel_list=$channel_list_51_side
+    stereo_mix=$stereo_mix_51_side
+    ;;
+  * )
+    exit 3
+    ;;
+esac
+
 # Check for all dependent files
 # Force hts-split to (re)make all if one is missing
-[[ ! -s "${work_prefix}-fc.wav" ]] || \
-[[ ! -s "${work_prefix}-fl.wav" ]] || \
-[[ ! -s "${work_prefix}-fr.wav" ]] || \
-[[ ! -s "${work_prefix}-lf.wav" ]] || \
-[[ ! -s "${work_prefix}-sl.wav" ]] || \
-[[ ! -s "${work_prefix}-sr.wav" ]] && \
-{
+files_ready=0;
+for channel in $channel_list; do
+  [[ -s "${work_prefix}-$channel.wav" ]] || files_ready=1;
+done
+[[ 0 = $files_ready ]] || {
   rm -f "${work_prefix}-fc.wav";
-  fixvid "hts-split";
+  echo "One, or more, of the channel files not found.";
+  echo "... Creating ...";
+  echo "";
+  time "$fixvid_dir/hts-split";
 }
 
-time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
-ffmpeg -hide_banner -loglevel error -stats -y \
-$input_flags -i \"${work_prefix}-fc.wav\" \
--map 0:0 -af \"$dyna_center\" \
--c:0 pcm_s16le -b:a 384k \
-$use_threads $output_flags \
-\"${work_prefix}-efc.wav\"";
 
-cat "fixvid-${work_prefix}.part" > "fixvid-${work_prefix}-normalize.log";
+# Process the regular channel files and make the enhanced versions
+for channel in $channel_list; do
+  case "$channel" in
+    'fl' | 'fr' )
+      encoding="-map 0:0 -af $dyna_front -c:0 pcm_s16le -b:a 384k $use_threads $output_flags"
+      ;;
+    'fc' )
+      encoding="-map 0:0 -af $dyna_center -c:0 pcm_s16le -b:a 384k $use_threads $output_flags"
+      ;;
+    *)
+      encoding="-map 0:0 -af $dyna_surround -c:0 pcm_s16le -b:a 384k $use_threads $output_flags"
+      ;;
+  esac
+  multi_launch "${channel^^} channel" bash -c "FFREPORT=file='fixvid-${work_prefix}-${channel}.part':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}-$channel.wav' $encoding '${work_prefix}-e$channel.wav'"
+done
 
-time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
-ffmpeg -hide_banner -loglevel error -stats -y \
-$input_flags -i \"${work_prefix}-fl.wav\" \
--map 0:0 -af \"$dyna_front\" \
--c:0 pcm_s16le -b:a 384k \
-$use_threads $output_flags \
-\"${work_prefix}-efl.wav\"";
+wait
 
-cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";
-
-time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
-ffmpeg -hide_banner -loglevel error -stats -y \
-$input_flags -i \"${work_prefix}-fr.wav\" \
--map 0:0 -af \"$dyna_front\" \
--c:0 pcm_s16le -b:a 384k \
-$use_threads $output_flags \
-\"${work_prefix}-efr.wav\"";
-
-cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";
-
-time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
-ffmpeg -hide_banner -loglevel error -stats -y \
-$input_flags -i \"${work_prefix}-lf.wav\" \
--map 0:0 -af \"$dyna_surround\" \
--c:0 pcm_s16le -b:a 384k \
-$use_threads $output_flags \
-\"${work_prefix}-elf.wav\"";
-
-cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";
-
-time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
-ffmpeg -hide_banner -loglevel error -stats -y \
-$input_flags -i \"${work_prefix}-sl.wav\" \
--map 0:0 -af \"$dyna_surround\" \
--c:0 pcm_s16le -b:a 384k \
-$use_threads $output_flags \
-\"${work_prefix}-esl.wav\"";
-
-cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";
-
-time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
-ffmpeg -hide_banner -loglevel error -stats -y \
-$input_flags -i \"${work_prefix}-sr.wav\" \
--map 0:0 -af \"$dyna_surround\" \
--c:0 pcm_s16le -b:a 384k \
-$use_threads $output_flags \
-\"${work_prefix}-esr.wav\"";
-
-cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";
-
-rm -f "fixvid-${work_prefix}.part"
+# Feed the individual log files into a single log file
+rm -f "fixvid-${work_prefix}-normalize.log";
+for channel in $channel_list; do
+  cat "fixvid-${work_prefix}-${channel}.part" >> "fixvid-${work_prefix}-normalize.log";
+  rm -f "fixvid-${work_prefix}-${channel}.part";
+done
diff --git a/hts-split b/hts-split
--- a/hts-split
+++ b/hts-split
@@ -30,15 +30,6 @@
 #                                                                      #
 ########################################################################
 
-##
-##      NOTE:
-##
-##  This file is only set up for processing of files related to a
-##  surround sound soundtrack of either 5.1 or 5.1(side). Any other type
-##  of surround sound setup, 7.1, etc., will require a complete set of
-##  command files to replace hts-split, hts-normalize, and hts-merge
-##
-
 #
 # Command script to extract the surround sound from a file and separate
 # the channels into independent files for later processing. Also saves
@@ -52,23 +43,21 @@
 #     surround_source file with the surround sound stream to use
 #     surround_stream the index (zero-based) of the surround stream
 #     surround_layout the name of the layout, as understood by ffmpeg
-#     channels        the filter used to split the stream into channels
+#     channel_map     the filter used to split the stream into channels
+#     channel_list    the list of channels to process
+#     stereo_mix      the ratios for mixing surround sound to stereo
 #     timestamp       entered in the creation_time metadata for streams
 #
 # Displays the ffmpeg progress line while running and the results of the
 # time command once finished.
 #
-# Generates 10 files:
-#     fixvid-*-split.cmd      The complete ffmpeg command to execute
-#     fixvid-*-split.log      The captured output of the ffmpeg command
-#     *-surround-fc.wav       The front center channel from the source
-#     *-surround-fl.wav       The front left channel from the source
-#     *-surround-fr.wav       The front right channel from the source
-#     *-surround-lf.wav       The low frequency channel from the source
-#     *-surround-sl.wav       The surround left channel from the source
-#     *-surround-sl.wav       The surround right channel from the source
-#     *-surround-aac          The copied surround soundtrack, AAC format
-#     *-surround-ac3          The copied surround soundtrack, AC3 format
+# Generates 5 files plus 1 per channel:
+#     fixvid-*-split-ac3.log       The captured output of ffmpeg
+#     fixvid-*-split-aa3.log       The captured output of ffmpeg
+#     fixvid-*-split-channels.log  The captured output of ffmpeg
+#     *-surround-aac               The copied surround sound, AAC format
+#     *-surround-ac3               The copied surround sound, AC3 format
+#     *-surround-*.wav             The * channel from the source
 #
 
 # Load the configuration file
@@ -86,58 +75,41 @@ work_prefix="${work_files}-surround";
 # To rerun, delete the *_surround_fc.wav file first
 [[ -s "${work_prefix}-fc.wav" ]] && exit 3;
 
-time bash -c "FFREPORT=file=\"fixvid-${work_prefix}-split.log\":level=40 \
-ffmpeg -hide_banner -y -loglevel error -stats \
-$input_flags -i \"$surround_source\" \\
--filter_complex '\
-  [0:$surround_stream] asplit=3 [CHANNELS][INTERNAL][EXTERNAL];\
-  [CHANNELS] channelsplit=channel_layout=$surround_layout [FL][FR][FC][LF][SL][SR]\
-' \
--map [FC] \
-$strip_meta_all $file_meta \
--metadata:s:0 language=eng -metadata:s:0 title='Center Front Channel' \
--c:0 pcm_s16le -b:a 384k \
-$audio_only $use_threads $output_flags \
-\"${work_prefix}-fc.wav\" \
--map [FL] \
-$strip_meta_all $file_meta \
--metadata:s:0 language=eng -metadata:s:0 title='Left Front Channel' \
--c:0 pcm_s16le -b:a 384k \
-$audio_only $use_threads $output_flags \
-\"${work_prefix}-fl.wav\" \
--map [FR] \
-$strip_meta_all $file_meta \
--metadata:s:0 language=eng -metadata:s:0 title='Right Front Channel' \
--c:0 pcm_s16le -b:a 384k \
-$audio_only $use_threads $output_flags \
-\"${work_prefix}-fr.wav\" \
--map [LF] \
-$strip_meta_all $file_meta \
--metadata:s:0 language=eng -metadata:s:0 title='Low-frequency Channel' \
--c:0 pcm_s16le -b:a 384k \
-$audio_only $use_threads $output_flags \
-\"${work_prefix}-lf.wav\" \
--map [SL] \
-$strip_meta_all $file_meta \
--metadata:s:0 language=eng -metadata:s:0 title='Left Surround Channel' \
--c:0 pcm_s16le -b:a 384k \
-$audio_only $use_threads $output_flags \
-\"${work_prefix}-sl.wav\" \
--map [SR] \
-$strip_meta_all $file_meta \
--metadata:s:0 language=eng -metadata:s:0 title='Right Surround Channel' \
--c:0 pcm_s16le -b:a 384k \
-$audio_only $use_threads $output_flags \
-\"${work_prefix}-sr.wav\" \
--map [EXTERNAL] \
-$strip_meta_all $file_meta \
--metadata:s:0 language=eng -metadata:s:0 title='5.1 Surround' \
--c:0 ac3 -b:a 640k \
-$audio_only $use_threads $output_flags \
-\"${work_prefix}.ac3\" \
--map [INTERNAL] \
-$strip_meta_all $file_meta \
--metadata:s:0 language=eng -metadata:s:0 title='5.1 Surround' \
--c:0 libfdk_aac -profile:a aac_he -b:a 384k \
-$audio_only $use_threads $output_flags \
-\"${work_prefix}.aac\"";
+# Set the channel data based on the chosen surround layout
+# Invalid, or missing, layout will abort the process
+case "$surround_layout" in
+  '7.1' )
+    channel_map=$channel_map_71
+    channel_list=$channel_list_71
+    stereo_mix=$stereo_mix_71
+    ;;
+  '5.1' )
+    channel_map=$channel_map_51
+    channel_list=$channel_list_51
+    stereo_mix=$stereo_mix_51
+    ;;
+  '5.1(side)' )
+    channel_map=$channel_map_51_side
+    channel_list=$channel_list_51_side
+    stereo_mix=$stereo_mix_51_side
+    ;;
+  * )
+    exit 3
+    ;;
+esac
+
+encoding="$strip_meta_all $file_meta -metadata:s:0 language=eng -c:0 pcm_s16le -b:a 384k $audio_only $use_threads $output_flags";
+
+for channel in $channel_list; do
+  channel_pad="[${channel^^}]";
+  pad_list="${pad_list}${channel_pad}";
+  channel_out="-map [${channel^^}] $encoding '${work_prefix}-${channel}.wav'"
+  out_list="${out_list} ${channel_out}";
+done
+
+multi_launch "Channel split" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-channels.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -filter_complex '[0:$surround_stream] channelsplit=channel_layout=$surround_layout $pad_list' $out_list";
+multi_launch "Original AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -map 0:$surround_stream $strip_meta_all $file_meta -metadata:s:0 language=eng -metadata:s:0 title='$surround_layout Surround' -c:0 ac3 -b:a 640k $audio_only $use_threads $output_flags '${work_prefix}.ac3'";
+# multi_launch "Original AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -map 0:$surround_stream $strip_meta_all $file_meta -metadata:s:0 language=eng -metadata:s:0 title='$surround_layout Surround' -c:0 libfdk_aac -profile:a aac_he -b:a 384k $audio_only $use_threads $output_flags '${work_prefix}.aac'";
+
+wait
+
