Enable processing of multiple audio streams
Converted the multiple video and subtitle processing algorithms for use
in processing the audio streams to enable the processing of more than
one audio stream.

Requires that the config file be modified to use suffix digits on the
audio settings in the same manner as the subtitles and video settings.

The conversion of the DTS stream creation remains to be done.

Signed-off-by: Ronald Lamoreaux <gitkey@chindraba.work>

diff --git a/hts-explode b/hts-explode
--- a/hts-explode
+++ b/hts-explode
@@ -39,53 +39,50 @@
 # Load the configuration file
 [[ -s fixvid.conf ]] && . fixvid.conf || exit 4;
 
-# Check for source file and replace with common source if missing
-if [[ 'x' == "x$surround_source" ]] && [[ -s $video_source ]]; then
-  surround_source=$video_source;
-fi
+# Load the helper functions and common settings
+source "$fixvid_dir/helpers";
 
-# Set the output filename base
-work_prefix="${work_files}-surround";
+group='audio';
+required='stream';
+group_fields="source stream label title lang layout channels include \
+dyna_center dyna_extras dyna_origin dyna_stereo mapping mixing";
 
-# Skip this if it has already been done.
-# To rerun, delete the *_surround_fc.wav file first
-[[ -s "${work_prefix}-fc.wav" ]] && exit 3;
+function do_explode {
+  # Test for surround sound and load surround sound settings
+  surround_sound_settings || return 0;
 
-# Set the channel data based on the chosen surround layout
-# Invalid, or missing, layout will abort the process
-case "$surround_layout" in
-  '7.1' )
-    channel_map=$channel_map_71
-    channel_list=$channel_list_71
-    stereo_mix=$stereo_mix_71
-    ;;
-  '5.1' )
-    channel_map=$channel_map_51
-    channel_list=$channel_list_51
-    stereo_mix=$stereo_mix_51
-    ;;
-  '5.1(side)' )
-    channel_map=$channel_map_51_side
-    channel_list=$channel_list_51_side
-    stereo_mix=$stereo_mix_51_side
-    ;;
-  * )
-    exit 3
-    ;;
-esac
+  # Check for, and set the title of the streams
+  [[ $audio_title ]] || audio_title="$video_title surround sound";
 
-encoding="$strip_meta_all $file_meta -metadata:s:0 language=eng -c:0 pcm_s16le -b:a 384k $audio_only $use_threads $output_flags";
+  # Skip this if it has already been done.
+  # To rerun, delete the *-fl.wav file first
+  [[ -s "${work_prefix}-fl.wav" ]] && return 0;
 
-for channel in $channel_list; do
-  channel_pad="[${channel^^}]";
-  pad_list="${pad_list}${channel_pad}";
-  channel_out="-map [${channel^^}] $encoding '${work_prefix}-${channel}.wav'"
-  out_list="${out_list} ${channel_out}";
-done
+  unset channels_out;
+  unset channel_out;
+  unset channel_pad;
+  unset pad_list;
+  for channel in $audio_layout; do
+    channel_pad="[${channel^^}]";
+    pad_list="${pad_list}${channel_pad}";
+    channel_out="-map [${channel^^}] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title ${channel^^} Channel' -c:0 pcm_s16le -b:a 384k $use_threads $audio_only $file_meta $output_flags '${work_prefix}-channels-${channel,,}.wav'"
+    channels_out="${channels_out} ${channel_out}";
+  done
 
-multi_launch "Channel split" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-channels.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -filter_complex '[0:$surround_stream] channelsplit=channel_layout=$surround_layout $pad_list' $out_list";
-multi_launch "Original AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -map 0:$surround_stream $strip_meta_all $file_meta -metadata:s:0 language=eng -metadata:s:0 title='$surround_layout Surround' -c:0 ac3 -b:a 640k $audio_only $use_threads $output_flags '${work_prefix}.ac3'";
-multi_launch "Original AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -map 0:$surround_stream $strip_meta_all $file_meta -metadata:s:0 language=eng -metadata:s:0 title='$surround_layout Surround' -c:0 libfdk_aac -profile:a aac_he -b:a 384k $audio_only $use_threads $output_flags '${work_prefix}.aac'";
+  # Create the AAC and/or AC3 files if they are missing.
+  # They don't need to be created after the first time
+  [[ 1 = $skip_aac ]] || [[ -s "${work_prefix}.aac" ]] || multi_launch "Original ${audio_label} AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-explode-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $audio_source -map 0:$audio_stream $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title' -c:0 libfdk_aac -profile:a aac_he -b:a 384k $audio_only $use_threads $output_flags '${work_prefix}.aac'";
+  [[ 1 = $skip_ac3 ]] || [[ -s "${work_prefix}.ac3" ]] || multi_launch "Original ${audio_label} AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-explode-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $audio_source -map 0:$audio_stream $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title' -c:0 ac3 -b:a 640k $audio_only $use_threads $output_flags '${work_prefix}.ac3'";
 
-wait
+  # Extract the channels
+  multi_launch "Split ${audio_label} channels" bash -c "FFREPORT=file='fixvid-${work_prefix}-explode-channels.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $audio_source -filter_complex '[0:$audio_stream] channelsplit=channel_layout=$audio_channels $pad_list' $channels_out";
+
+  wait
+}
+
+# Read the optional argument.
+[[ $1 ]] && target_num=$1 || target_num=0;
+
+process_group do_explode $group $required $target_num $group_fields;
+exit "$?";
 
diff --git a/hts-normalize b/hts-normalize
--- a/hts-normalize
+++ b/hts-normalize
@@ -39,72 +39,64 @@
 # Load the configuration file
 [[ -s fixvid.conf ]] && . fixvid.conf || exit 4;
 
-# Set the output filename base
-work_prefix="${work_files}-surround";
+# Load the helper functions and common settings
+source "$fixvid_dir/helpers";
 
-# Skip this if it has already been done.
-# To rerun, delete the *_surround_fce.wav file first
-[[ -s "${work_prefix}_efc.wav" ]] && exit 3;
+group='audio';
+required='stream';
+group_fields="source stream label title lang layout channels include \
+dyna_center dyna_extras dyna_origin dyna_stereo mapping mixing";
 
-# Set the channel data based on the chosen surround layout
-# Invalid, or missing, layout will abort the process
-case "$surround_layout" in
-  '7.1' )
-    channel_map=$channel_map_71
-    channel_list=$channel_list_71
-    stereo_mix=$stereo_mix_71
-    ;;
-  '5.1' )
-    channel_map=$channel_map_51
-    channel_list=$channel_list_51
-    stereo_mix=$stereo_mix_51
-    ;;
-  '5.1(side)' )
-    channel_map=$channel_map_51_side
-    channel_list=$channel_list_51_side
-    stereo_mix=$stereo_mix_51_side
-    ;;
-  * )
-    exit 3
-    ;;
-esac
+function do_normalize {
+  # Test for surround sound and load surround sound settings
+  surround_sound_settings || return 0;
 
-# Check for all dependent files
-# Force hts-explode to (re)make all if one is missing
-files_ready=0;
-for channel in $channel_list; do
-  [[ -s "${work_prefix}-$channel.wav" ]] || files_ready=1;
-done
-[[ 0 = $files_ready ]] || {
-  rm -f "${work_prefix}-fc.wav";
-  echo "One, or more, of the channel files not found.";
-  echo "... Creating ...";
-  echo "";
-  "$fixvid_dir/hts-explode";
+  # Skip this if it has already been done.
+  # To rerun, delete the *-channels-adj-fl.wav file first
+  [[ -s "${work_prefix}-channels-adj-fl.wav" ]] && return 0;
+
+  # Check for all dependent files
+  # Force hts-explode to (re)make all if one is missing
+  files_ready=0;
+  for channel in $audio_layout; do
+    [[ -s "${work_prefix}-channels-$channel.wav" ]] || files_ready=1;
+  done
+  [[ 0 = $files_ready ]] || {
+    rm -f "${work_prefix}-channels-fl.wav";
+    echo "One, or more, of the channel files not found.";
+    echo "... Creating ...";
+    echo "";
+    "$fixvid_dir/hts-explode" $group_num;
+  }
+
+  # Process the regular channel files and make the enhanced versions
+  for channel in $audio_layout; do
+    case "$channel" in
+      'fl' | 'fr' )
+        channel_dyna="$audio_dyna_origin"
+        ;;
+      'fc' )
+        channel_dyna="$audio_dyna_center"
+        ;;
+      *)
+        channel_dyna="$audio_dyna_extras"
+        ;;
+    esac
+    multi_launch "Normalize ${audio_label} ${channel^^} channel" bash -c "FFREPORT=file='fixvid-${work_prefix}-${channel}.part':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}-channels-$channel.wav' -map 0:0 -af $audio_dyna_origin $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title [${channel^^}] (Enhanced)' -c:0 pcm_s16le -b:a 384k $use_threads $file_meta $output_flags '${work_prefix}-channels-adj-$channel.wav'"
+  done
+
+  wait
+
+  # Feed the individual log files into a single log file
+  rm -f "fixvid-${work_prefix}-normalize.log";
+  for channel in $audio_layout; do
+    cat "fixvid-${work_prefix}-${channel}.part" >> "fixvid-${work_prefix}-normalize.log";
+    rm -f "fixvid-${work_prefix}-${channel}.part";
+  done
 }
 
+# Read the optional argument.
+[[ $1 ]] && target_num=$1 || target_num=0;
 
-# Process the regular channel files and make the enhanced versions
-for channel in $channel_list; do
-  case "$channel" in
-    'fl' | 'fr' )
-      encoding="-map 0:0 -af $dyna_front -c:0 pcm_s16le -b:a 384k $use_threads $output_flags"
-      ;;
-    'fc' )
-      encoding="-map 0:0 -af $dyna_center -c:0 pcm_s16le -b:a 384k $use_threads $output_flags"
-      ;;
-    *)
-      encoding="-map 0:0 -af $dyna_surround -c:0 pcm_s16le -b:a 384k $use_threads $output_flags"
-      ;;
-  esac
-  multi_launch "${channel^^} channel" bash -c "FFREPORT=file='fixvid-${work_prefix}-${channel}.part':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}-$channel.wav' $encoding '${work_prefix}-e$channel.wav'"
-done
+process_group do_normalize $group $required $target_num $group_fields;
 
-wait
-
-# Feed the individual log files into a single log file
-rm -f "fixvid-${work_prefix}-normalize.log";
-for channel in $channel_list; do
-  cat "fixvid-${work_prefix}-${channel}.part" >> "fixvid-${work_prefix}-normalize.log";
-  rm -f "fixvid-${work_prefix}-${channel}.part";
-done
diff --git a/hts-remix b/hts-remix
--- a/hts-remix
+++ b/hts-remix
@@ -38,60 +38,58 @@
 # Load the configuration file
 [[ -s fixvid.conf ]] && . fixvid.conf || exit 4;
 
-# Set the output filename base
-work_prefix="${work_files}-surround";
+# Load the helper functions and common settings
+source "$fixvid_dir/helpers";
 
-# Skip this if it has already been done.
-# To rerun, delete the *_surround_adjusted.ac3 file first
-[[ -s "${work_prefix}-adjusted.ac3" ]] && exit 3;
+group='audio';
+required='stream';
+group_fields="source stream label title lang layout channels include \
+dyna_center dyna_extras dyna_origin dyna_stereo mapping mixing";
 
-# Set the channel data based on the chosen surround layout
-# Invalid, or missing, layout will abort the process
-case "$surround_layout" in
-  '7.1' )
-    channel_map=$channel_map_71
-    channel_list=$channel_list_71
-    stereo_mix=$stereo_mix_71
-    ;;
-  '5.1' )
-    channel_map=$channel_map_51
-    channel_list=$channel_list_51
-    stereo_mix=$stereo_mix_51
-    ;;
-  '5.1(side)' )
-    channel_map=$channel_map_51_side
-    channel_list=$channel_list_51_side
-    stereo_mix=$stereo_mix_51_side
-    ;;
-  * )
-    exit 3
-    ;;
-esac
+function do_remix {
+  # Test for surround sound and load surround sound settings
+  surround_sound_settings || return 0;
 
-# Check for all dependent files
-# Force hts-normalize to (re)make all if one is missing
-files_ready=0;
-for channel in $channel_list; do
-  [[ -s "${work_prefix}-e$channel.wav" ]] || files_ready=1;
-done
-[[ 0 = $files_ready ]] || {
-  rm -f "${work_prefix}-efc.wav";
-  echo "Normalized files not found.";
-  echo " ... Creating ...";
-  echo "";
-  "$fixvid_dir/hts-normalize";
+  # Skip this if it has already been done.
+  # To rerun, delete the *-remix.ac3 file first
+  [[ -s "${work_prefix}-remix.ac3" ]] && return 0;
+
+  # Check for all dependent files
+  # Force hts-normalize to (re)make all if one is missing
+  files_ready=0;
+  for channel in $audio_layout; do
+    [[ -s "${work_prefix}-channels-adj-$channel.wav" ]] || files_ready=1;
+  done
+  [[ 0 = $files_ready ]] || {
+    rm -f "${work_prefix}-channels-adj-fl.wav";
+    echo "Normalized files not found.";
+    echo " ... Creating ...";
+    echo "";
+    "$fixvid_dir/hts-normalize" $group_num;
+  }
+
+  unset channels_in;
+  unset channel_in;
+  unset channel_pad;
+  unset pad_list;
+  channel_count=0;
+  for channel in $audio_layout; do
+    channel_in="$input_flags -i ${work_prefix}-channels-adj-${channel}.wav";
+    channel_pad="[$channel_count:0]";
+    channels_in="${channels_in} ${channel_in}";
+    pad_list="${pad_list}${channel_pad}";
+    channel_count=$(( $channel_count + 1 ));
+  done
+
+  [[ 1 = $skip_aac ]] || multi_launch "Enhance ${audio_label} AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-remix-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $channels_in -filter_complex '$pad_list amerge=inputs=$channel_count [CHANNELS];[CHANNELS] $audio_maping [OUT]' -map [OUT] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title (Enhanced)' -c:0 libfdk_aac -profile:a aac_he -b:a 384k $use_threads $file_meta '${work_prefix}-remix.aac'";
+  [[ 1 = $skip_ac3 ]] || multi_launch "Enhance ${audio_label} AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-remix-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $channels_in -filter_complex '$pad_list amerge=inputs=$channel_count [CHANNELS];[CHANNELS] $audio_maping [OUT]' -map [OUT] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_title (Enhanced)' -c:0 ac3 -b:a 640k $use_threads $file_meta '${work_prefix}-remix.ac3'";
+
+  wait
 }
 
-channel_count=0;
-for channel in $channel_list; do
-  channel_pad="[$channel_count:0]";
-  channel_count=$(( $channel_count + 1 ));
-  pad_list="${pad_list}${channel_pad}";
-  channel_in="$input_flags -i ${work_prefix}-e${channel}.wav";
-  in_list="${in_list} ${channel_in}";
-done
 
-multi_launch "Enhanced AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-merge-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $in_list -filter_complex '$pad_list amerge=inputs=$channel_count [CHANNELS];[CHANNELS] $channel_map [OUT]' -map [OUT] $strip_meta_all $file_meta -metadata:s:0 language=eng -metadata:s:0 title='$surround_layout Surround (Enhanced)' -c:0 libfdk_aac -profile:a aac_he -b:a 384k $use_threads $file_meta '${work_prefix}-adjusted.aac'";
-multi_launch "Enhanced AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-merge-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $in_list -filter_complex '$pad_list amerge=inputs=$channel_count [CHANNELS];[CHANNELS] $channel_map [OUT]' -map [OUT] $strip_meta_all $file_meta -metadata:s:0 language=eng -metadata:s:0 title='$surround_layout Surround (Enhanced)' -c:0 ac3 -b:a 640k $use_threads $file_meta '${work_prefix}-adjusted.ac3'";
+# Read the optional argument.
+[[ $1 ]] && target_num=$1 || target_num=0;
 
-wait
+process_group do_remix $group $required $target_num $group_fields;
+
